"""Review CLI: interactive proposal review and approval for VaultLens v0.2.

Provides interactive terminal interface to approve, reject, edit, or skip
edge proposals generated by the proposer.
"""

import sqlite3
import json
import sys
import os
from pathlib import Path
from typing import Optional


def review_proposals(db_path: str, write_markdown: bool = False) -> dict:
    """Interactive review of pending proposals.

    Args:
        db_path: Path to SQLite database
        write_markdown: If True, write approved edges into markdown files

    Returns:
        Dict with review statistics
    """
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row

    cursor = conn.execute("""
        SELECT * FROM proposals
        WHERE status = 'pending'
        ORDER BY confidence DESC, created_at ASC
    """)
    pending = list(cursor)

    if not pending:
        print("No pending proposals to review.")
        conn.close()
        return {"reviewed": 0, "approved": 0, "rejected": 0, "skipped": 0}

    print(f"\n{'='*60}")
    print(f"  VaultLens Proposal Review — {len(pending)} pending")
    print(f"{'='*60}")
    print(f"  [a] approve  [r] reject  [s] skip  [e] edit  [d] duplicate  [q] quit")
    print(f"  [p] approve + write to markdown")
    print(f"{'='*60}\n")

    reviewed = 0
    approved = 0
    rejected = 0
    skipped = 0

    for proposal in pending:
        pid = proposal["proposal_id"]
        source = proposal["source_title"]
        target = proposal["target_title"]
        relation = proposal["relation"]
        variant = proposal["variant"]
        confidence = proposal["confidence"]
        evidence = proposal["evidence_span"]
        rationale = proposal["rationale"]
        proposer = proposal["proposer"]

        print(f"── Proposal {reviewed + 1}/{len(pending)} ──")
        print(f"  Source:     {source}")
        print(f"  Target:     {target}")
        print(f"  Relation:   {relation}")
        print(f"  Variant:    {variant}")
        print(f"  Confidence: {confidence:.2f}")
        print(f"  Proposer:   {proposer}")
        if evidence:
            print(f"  Evidence:   \"{evidence[:120]}{'...' if len(evidence) > 120 else ''}\"")
        if rationale:
            print(f"  Rationale:  {rationale}")
        print()

        action = input("  Action [a/r/s/e/d/p/q]: ").strip().lower()

        if action == "q":
            print("\n  Quitting review. Remaining proposals stay pending.")
            break
        elif action == "a" or action == "p":
            status = "approved"
            approved += 1
            # Write to markdown if requested
            if action == "p" or write_markdown:
                _write_edge_to_markdown(db_path, proposal)
            # Also append to approved_edges.jsonl
            _append_to_approved_jsonl(db_path, proposal)

        elif action == "r":
            status = "rejected"
            rejected += 1
        elif action == "s":
            status = "pending"
            skipped += 1
            print("  (skipped)\n")
            continue
        elif action == "e":
            # Edit mode
            new_target = input(f"  New target [{target}]: ").strip()
            new_relation = input(f"  New relation [{relation}]: ").strip()
            if new_target:
                target = new_target
                # Re-resolve variant from relation
                from .parser import RELATION_TO_VARIANT
                variant = RELATION_TO_VARIANT.get(new_relation, "generic") if new_relation else variant
            if new_relation:
                relation = new_relation
            conn.execute("""
                UPDATE proposals SET target_title = ?, relation = ?, variant = ?
                WHERE proposal_id = ?
            """, (target, relation, variant, pid))
            print(f"  Updated: {source} --{relation}--> {target}")
            status = "approved"
            approved += 1
            # Also write to approved JSONL
            _append_to_approved_jsonl(db_path, {
                "source_title": source,
                "target_title": target,
                "relation": relation,
                "variant": variant,
                "confidence": confidence,
                "evidence_span": evidence,
                "proposal_id": pid,
                "source_note_id": proposal["source_note_id"],
            })

        elif action == "d":
            status = "duplicate"
            rejected += 1
        else:
            print(f"  Unknown action '{action}', skipping.")
            skipped += 1
            continue

        # Update proposal status
        conn.execute("""
            UPDATE proposals SET status = ?, reviewed_at = datetime('now')
            WHERE proposal_id = ?
        """, (status, pid))
        conn.commit()

        reviewed += 1
        print(f"  -> {status.upper()}\n")

    stats = {
        "reviewed": reviewed,
        "approved": approved,
        "rejected": rejected,
        "skipped": skipped,
    }

    print(f"\n{'='*60}")
    print(f"  Review complete: {approved} approved, {rejected} rejected, {skipped} skipped")
    print(f"{'='*60}\n")

    conn.close()
    return stats


def _write_edge_to_markdown(db_path: str, proposal: dict) -> None:
    """Write a typed relation directly into the source markdown file.

    Appends the typed relation line at end of file.
    """
    source_id = proposal.get("source_note_id")
    if not source_id:
        return

    conn = sqlite3.connect(db_path)
    cursor = conn.execute("SELECT file_path FROM notes WHERE note_id = ?", (source_id,))
    row = cursor.fetchone()
    conn.close()

    if not row:
        return

    file_path = row[0]
    # Resolve relative to vault root
    db_dir = os.path.dirname(db_path)
    # Try relative to db, then relative to cwd
    for base in [db_dir, os.getcwd(), os.path.dirname(db_dir)]:
        full_path = os.path.join(base, file_path)
        if os.path.exists(full_path):
            break
    else:
        return

    target = proposal["target_title"]
    relation = proposal["relation"]

    # Read existing content
    with open(full_path, "r", encoding="utf-8") as f:
        content = f.read()

    # Check if edge already exists
    edge_line = f"\n{target} {relation}:: [[{target}]]"
    if edge_line in content:
        return

    # Append to end of file
    with open(full_path, "a", encoding="utf-8") as f:
        f.write(edge_line + "\n")


def _append_to_approved_jsonl(db_path: str, proposal: dict) -> None:
    """Append approved edge to .vaultlens/approved_edges.jsonl with optional signature."""
    db_dir = os.path.dirname(db_path)
    vaultlens_dir = os.path.join(db_dir, ".vaultlens")
    os.makedirs(vaultlens_dir, exist_ok=True)

    jsonl_path = os.path.join(vaultlens_dir, "approved_edges.jsonl")

    record = {
        "source_title": proposal.get("source_title", ""),
        "target": proposal.get("target_title", proposal.get("target", "")),
        "relation": proposal.get("relation", ""),
        "variant": proposal.get("variant", ""),
        "confidence": proposal.get("confidence", 0.5),
        "evidence_span": proposal.get("evidence_span", ""),
        "proposal_id": proposal.get("proposal_id", ""),
        "approved_at": "",
    }

    import datetime
    record["approved_at"] = datetime.datetime.now().isoformat()

    # Sign if secret is available
    from .proposal_security import sign_proposal, get_secret
    secret = get_secret()
    if secret:
        record["signature"] = sign_proposal(record, secret)

    with open(jsonl_path, "a", encoding="utf-8") as f:
        f.write(json.dumps(record) + "\n")
